spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: love202020
    url: jdbc:mysql://localhost:3306/universe
  # session timeout
  session:
    timeout: 100000

